# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Result check

on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - 'main'
    paths:
      - 'msdt-3/**'
      
permissions:
  contents: write
  
jobs:
  check-result:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ActionsTools/read-json-action@main
        name: acquiring your results
        id: your_results
        with:
         file_path: "msdt-3/result.json"       
      - name: displaying your results
        run: |
          echo "your variant: ${{steps.your_results.outputs.variant}}"
          echo "your checksum: ${{steps.your_results.outputs.checksum}}" 
      - name: checking your results 
        run: |
          array=${{ secrets.CHECKSUMS }}
          sum=${{steps.your_results.outputs.checksum}}
          vnt=${{steps.your_results.outputs.variant}}
          cnt=0
          for item in ${array[*]}
          do
          cnt=$((cnt+1))
          if [[ $item == $sum ]]; then
              if [[ $cnt == $vnt ]]; then
                echo "Congratulations, your results are correct"
                exit 0
              fi
          fi
          done
          echo "Your results are not correct. Correct checksum for your variant is ${array[$vnt-1]}"
          exit 1
